# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ Staging ]
  # pull_request:
   #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Decrypting Server Key
        shell: bash
        run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}
      - name: Authorizing Org
        uses: forcedotcom/salesforcedx-actions@master
        with:
            args: force:auth:jwt:grant --clientid ${{ secrets.TARGET_CONSUMER_KEY }} --jwtkeyfile assets/server.key --username ${{ secrets.TARGET_USER_NAME }} --setdefaultusername
      #- name: "Install App and Create Delta"   
      #  run: |  
      #     sudo npm install sfdx-git-delta@latest -g
      #     git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
      #     git fetch --all
      #     git checkout -b pr          
      #     git --no-pager diff --name-status pr origin/Staging
      #     sgd --to pr  --from origin/Staging --repo . --output .
      #     echo "--- package.xml generated with added and modified metadata ---"
      #     cat package/package.xml   
      - name: Deploying Metadata
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: force:source:deploy -x package/package.xml
